# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

complexity:
  LongMethod:
    threshold: 80
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20
  LongParameterList:
    functionThreshold: 7
  CyclomaticComplexMethod:
    threshold: 25
style:
  ReturnCount:
    max: 5
  MagicNumber:
    ignoreEnums: true
